Bump QT_MIN_VERSION and KF5_MIN_VERSION
Summary:
28754fa2d95e broke compiling Gwenview with Qt 5.6:
```
lib/historymodel.cpp: In member function ‘void Gwenview::HistoryModelPrivate::load()’:
lib/historymodel.cpp:170:72: error: lambda-expression in unevaluated context
         Q_FOREACH(const QString & name, dir.entryList(QStringList() << QStringLiteral("*rc"))) {
```

Given that at some point we had to move on to a newer Qt anyway, we
might as well do that now. Since Qt 5.9 is an LTS release and available
in the stable versions of major distros [1], it seems like a good fit.
Okular and Dolphin are already asking for Qt 5.8 too (but Qt 5.8 is
neither supported nor widely used anymore).

While at it, we also bump the KF5 version, to make testing the oldest
supported baseline easier and allow for some `#ifdef` cleanup later on.
Here 5.43 seems like a good choice [2] (Dolphin uses the same version).

[1] https://repology.org/metapackage/qt5-base/versions
[2] https://repology.org/metapackage/kwidgetsaddons/versions

Test Plan: Should still compile on openSUSE Leap 15.0 and Ubuntu 18.04.

Reviewers: #gwenview, ngraham

Reviewed By: #gwenview, ngraham

Subscribers: ngraham

Differential Revision: https://phabricator.kde.org/D14700